// Extract all joint builder data for Firebase migration
// This file maps the current hardcoded data to a Firebase-compatible structure

export const jointBuilderSteps = [
  {
    id: "step1",
    sortOrder: 1,
    name: "Select Rolling Paper",
    description: "Choose your paper type and capacity",
    stepType: "paper",
    active: true,
  },
  {
    id: "step2",
    sortOrder: 2,
    name: "Choose Your Filter",
    description: "Select the filter tip for optimal airflow",
    stepType: "filter",
    active: true,
  },
  {
    id: "step3",
    sortOrder: 3,
    name: "Customize Your Filling",
    description: "Mix your perfect blend",
    stepType: "filling",
    active: true,
  },
  {
    id: "step4",
    sortOrder: 4,
    name: "External Customization",
    description: "Add premium coatings or wraps",
    stepType: "external",
    active: true,
  },
  {
    id: "step5",
    sortOrder: 5,
    name: "Review Your Custom Joint",
    description: "Double-check everything before adding to cart",
    stepType: "review",
    active: true,
  },
];

// Step 1: Paper Options
export const paperOptions = [
  {
    id: "pre-rolled-ck",
    name: "Pre-Rolled Cone",
    description: "Classic cone shape, ready to fill",
    stepId: "step1",
    sortOrder: 1,
    color: "from-amber-100 to-amber-200",
    icon: "CONE",
    active: true,
    hasBuiltInFilter: true,
    selectionType: "variant", // "variant" or "slider"
    variants: [
      {
        id: "small",
        name: "Small",
        capacity: 0.4,
        price: 1,
        label: "Small (0.4g)",
        sortOrder: 1,
      },
      {
        id: "medium",
        name: "Medium",
        capacity: 0.8,
        price: 3,
        label: "Medium (0.8g)",
        sortOrder: 2,
      },
      {
        id: "big",
        name: "Big",
        capacity: 1.2,
        price: 5,
        label: "Big (1.2g)",
        sortOrder: 3,
      },
    ],
  },
  {
    id: "blunt-hemp-wrap",
    name: "Blunt/Hemp Wraps",
    description: "Natural hemp leaf wrap",
    stepId: "step1",
    sortOrder: 2,
    color: "from-green-700 to-green-800",
    icon: "HEMP",
    active: true,
    hasBuiltInFilter: false,
    selectionType: "variant",
    variants: [
      {
        id: "standard",
        name: "Standard",
        capacity: 1.5,
        price: 60,
        label: "Standard (1.5g)",
        sortOrder: 1,
      },
      {
        id: "blackwood",
        name: "Blackwood",
        capacity: 2.0,
        price: 95,
        label: "Blackwood (2.0g)",
        sortOrder: 2,
      },
      {
        id: "hemp-cone",
        name: "Hemp Cone",
        capacity: 1.0,
        price: 25,
        label: "Hemp Cone (1.0g)",
        sortOrder: 3,
      },
    ],
  },
  {
    id: "standard-rolling-paper",
    name: "Standard Rolling Paper",
    description: "Various flavored rolling papers",
    stepId: "step1",
    sortOrder: 3,
    color: "from-blue-100 to-blue-200",
    icon: "PAPER",
    active: true,
    hasBuiltInFilter: false,
    selectionType: "variant",
    variants: [
      {
        id: "weed-th",
        name: "Weed TH",
        capacity: 1.0,
        price: 5,
        label: "Weed TH (1.0g)",
        sortOrder: 1,
      },
      {
        id: "elements",
        name: "Elements",
        capacity: 1.0,
        price: 5,
        label: "Elements (1.0g)",
        sortOrder: 2,
      },
      {
        id: "smoking-blue",
        name: "Smoking Blue",
        capacity: 1.5,
        price: 5,
        label: "Smoking Blue (1.5g)",
        sortOrder: 3,
      },
      {
        id: "orange-flavour",
        name: "Orange Flavour",
        capacity: 1.0,
        price: 5,
        label: "Orange Flavour (1.0g)",
        sortOrder: 4,
      },
      {
        id: "watermelon-flavour",
        name: "Watermelon Flavour",
        capacity: 1.0,
        price: 5,
        label: "Watermelon Flavour (1.0g)",
        sortOrder: 5,
      },
      {
        id: "chocolate-flavour",
        name: "Chocolate Flavour",
        capacity: 1.0,
        price: 5,
        label: "Chocolate Flavour (1.0g)",
        sortOrder: 6,
      },
    ],
  },
  {
    id: "rolling-paper-custom",
    name: "Rolling Paper (Custom)",
    description: "Adjust length for custom capacity (2g+)",
    stepId: "step1",
    sortOrder: 4,
    color: "from-gray-100 to-gray-200",
    icon: "PAPER",
    active: true,
    hasBuiltInFilter: false,
    selectionType: "slider",
    sliderConfig: {
      minValue: 7,
      maxValue: 20,
      step: 1,
      unit: "cm",
      basePrice: 20,
      pricePerUnit: 3,
      capacityFormula: "(value / 7) * 2", // capacity = (length / 7) * 2
    },
  },
  {
    id: "golden-paper",
    name: "Golden Rolling Paper",
    description: "Premium gold-infused paper",
    stepId: "step1",
    sortOrder: 5,
    color: "from-yellow-400 to-amber-500",
    icon: "GOLD",
    active: true,
    hasBuiltInFilter: false,
    selectionType: "variant",
    variants: [
      {
        id: "premium",
        name: "Premium",
        capacity: 1.0,
        price: 150,
        label: "Premium (1.0g)",
        sortOrder: 1,
      },
    ],
  },
  {
    id: "glass-cone",
    name: "Glass Cone",
    description: "Premium glass cone",
    stepId: "step1",
    sortOrder: 6,
    color: "from-cyan-200 to-blue-300",
    icon: "CONE",
    active: true,
    hasBuiltInFilter: true,
    selectionType: "variant",
    variants: [
      {
        id: "glass",
        name: "Glass",
        capacity: 1.0,
        price: 150,
        label: "Glass (1.0g)",
        sortOrder: 1,
      },
    ],
  },
];

// Step 2: Filter Options
export const filterOptions = [
  {
    id: "paper-filter",
    name: "Paper Filter",
    description: "Classic cardboard tip, smooth draw",
    stepId: "step2",
    sortOrder: 1,
    icon: "PAPER",
    color: "from-amber-50 to-amber-100",
    active: true,
    glassSize: null,
    selectionType: "variant",
    variants: [
      { id: "small", name: "Small", price: 5, label: "Small", sortOrder: 1 },
      { id: "medium", name: "Medium", price: 5, label: "Medium", sortOrder: 2 },
      { id: "large", name: "Large", price: 5, label: "Large", sortOrder: 3 },
    ],
  },
  {
    id: "slim-glass",
    name: "Slim Glass Filter (10mm)",
    description: "Elegant glass tip, cooler smoke",
    stepId: "step2",
    sortOrder: 2,
    icon: "SLIM",
    color: "from-blue-200 to-cyan-200",
    price: 25,
    active: true,
    glassSize: "10mm",
    selectionType: "direct",
  },
  {
    id: "wide-glass",
    name: "Wide Glass Filter (12mm)",
    description: "Premium wide glass, maximum airflow",
    stepId: "step2",
    sortOrder: 3,
    icon: "WIDE",
    color: "from-indigo-200 to-green-200",
    price: 35,
    active: true,
    glassSize: "12mm",
    selectionType: "direct",
  },
];

// Step 3: Filling Options - Worm
export const wormOptions = [
  {
    id: "hash-worm",
    name: "Hash Worm",
    description: "Premium hash center spiral",
    stepId: "step3",
    category: "worm",
    sortOrder: 1,
    basePrice: 100,
    active: true,
    weightFormula: "capacity * 0.15", // 15% of capacity
  },
  {
    id: "rosin-donut",
    name: "Rosin Donut",
    description: "Live rosin center ring",
    stepId: "step3",
    category: "worm",
    sortOrder: 2,
    basePrice: 150,
    active: true,
    weightFormula: "capacity * 0.15",
  },
];

// Step 3: Filling Options - Flower
export const flowerOptions = [
  {
    id: "thai-stick",
    name: "Thai Stick",
    type: "Sativa",
    description: "Energetic, uplifting",
    stepId: "step3",
    category: "flower",
    sortOrder: 1,
    pricePerGram: 150,
    active: true,
  },
  {
    id: "blueberry-kush",
    name: "Blueberry Kush",
    type: "Indica",
    description: "Relaxing, sweet berry",
    stepId: "step3",
    category: "flower",
    sortOrder: 2,
    pricePerGram: 180,
    active: true,
  },
  {
    id: "og-kush",
    name: "OG Kush",
    type: "Hybrid",
    description: "Balanced, earthy",
    stepId: "step3",
    category: "flower",
    sortOrder: 3,
    pricePerGram: 200,
    active: true,
  },
  {
    id: "super-lemon-haze",
    name: "Super Lemon Haze",
    type: "Sativa",
    description: "Citrus, energetic",
    stepId: "step3",
    category: "flower",
    sortOrder: 4,
    pricePerGram: 220,
    active: true,
  },
  {
    id: "northern-lights",
    name: "Northern Lights",
    type: "Indica",
    description: "Deep relaxation",
    stepId: "step3",
    category: "flower",
    sortOrder: 5,
    pricePerGram: 190,
    active: true,
  },
  {
    id: "white-widow",
    name: "White Widow",
    type: "Hybrid",
    description: "Euphoric, creative",
    stepId: "step3",
    category: "flower",
    sortOrder: 6,
    pricePerGram: 210,
    active: true,
  },
];

// Step 3: Filling Options - Hash
export const hashOptions = [
  {
    id: "moroccan-hash",
    name: "Moroccan Hash",
    description: "Traditional, earthy",
    stepId: "step3",
    category: "hash",
    sortOrder: 1,
    pricePerGram: 300,
    active: true,
  },
  {
    id: "afghan-hash",
    name: "Afghan Hash",
    description: "Premium quality",
    stepId: "step3",
    category: "hash",
    sortOrder: 2,
    pricePerGram: 350,
    active: true,
  },
  {
    id: "bubble-hash",
    name: "Bubble Hash",
    description: "Ice water extract",
    stepId: "step3",
    category: "hash",
    sortOrder: 3,
    pricePerGram: 400,
    active: true,
  },
  {
    id: "charas",
    name: "Charas",
    description: "Hand-rolled, sticky",
    stepId: "step3",
    category: "hash",
    sortOrder: 4,
    pricePerGram: 380,
    active: true,
  },
];

// Step 4: External Options - Coating
export const externalCoatingOptions = [
  {
    id: "kief-coating",
    name: "Kief Coating",
    description: "Crystal trichome dust",
    stepId: "step4",
    category: "coating",
    sortOrder: 1,
    price: 100,
    active: true,
    color: "linear-gradient(135deg, #10b981 0%, #34d399 100%)",
  },
  {
    id: "oil-coating",
    name: "Oil Coating",
    description: "Premium cannabis oil",
    stepId: "step4",
    category: "coating",
    sortOrder: 2,
    price: 150,
    active: true,
    color: "linear-gradient(135deg, #f97316 0%, #fb923c 100%)",
  },
  {
    id: "rosin-full-dip",
    name: "Rosin Full Dip",
    description: "Complete rosin coating",
    stepId: "step4",
    category: "coating",
    sortOrder: 3,
    price: 200,
    active: true,
    color: "linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)",
  },
  {
    id: "rosin-kief-combo",
    name: "Rosin + Kief Combo",
    description: "Ultimate enhancement",
    stepId: "step4",
    category: "coating",
    sortOrder: 4,
    price: 250,
    active: true,
    color: "linear-gradient(135deg, #a855f7 0%, #ec4899 50%, #fbbf24 100%)",
  },
];

// Step 4: External Options - Wrap
export const externalWrapOptions = [
  {
    id: "rosin-spiral",
    name: "Rosin Spiral",
    description: "Decorative rosin swirl",
    stepId: "step4",
    category: "wrap",
    sortOrder: 1,
    price: 150,
    active: true,
    image: "/CustomJoint/tip-spiral.png",
  },
  {
    id: "hash-M",
    name: 'Hash "M" Wrap',
    description: "Hash letter decoration",
    stepId: "step4",
    category: "wrap",
    sortOrder: 2,
    price: 100,
    active: true,
    image: "/CustomJoint/tip-M.png",
  },
  {
    id: "rosin-M",
    name: 'Rosin "M" Wrap',
    description: "Rosin letter decoration",
    stepId: "step4",
    category: "wrap",
    sortOrder: 3,
    price: 120,
    active: true,
    image: "/CustomJoint/tip-M.png",
  },
];

// Compatibility Rules (which filters work with which papers)
export const compatibilityRules = [
  {
    id: "rule1",
    paperType: "pre-rolled-ck",
    allowedFilters: [], // Built-in filter
    skipFilterStep: true,
  },
  {
    id: "rule2",
    paperType: "glass-cone",
    allowedFilters: [], // Built-in filter
    skipFilterStep: true,
  },
  {
    id: "rule3",
    paperType: "blunt-hemp-wrap",
    allowedFilters: ["paper-filter", "wide-glass"], // Paper or 12mm glass
  },
  {
    id: "rule4",
    paperType: "golden-paper",
    allowedFilters: ["paper-filter", "slim-glass"], // Paper or 10mm glass
  },
  {
    id: "rule5",
    paperType: "rolling-paper-custom",
    condition: "length <= 12",
    allowedFilters: ["paper-filter", "slim-glass"],
  },
  {
    id: "rule6",
    paperType: "rolling-paper-custom",
    condition: "length > 12 && length <= 16",
    allowedFilters: ["paper-filter"],
  },
  {
    id: "rule7",
    paperType: "rolling-paper-custom",
    condition: "length > 16",
    allowedFilters: ["paper-filter"],
  },
  {
    id: "rule8",
    paperType: "standard-rolling-paper",
    allowedFilters: ["paper-filter", "slim-glass", "wide-glass"],
  },
];
